domain: visualisation.io
title: Visualisation

menu:
  - url: dim
    name: Map dimension
    global: false

  - url: https://en.wikipedia.org/wiki/A*_search_algorithm
    name: How it works
    global: true

  - url: last
    name: Last computing
    global: false
