domain: visualisation.io
title: Visualisation

menu:
  - url: dim
    name: Map dimension

  - url: https://en.wikipedia.org/wiki/A*_search_algorithm
    name: How it works

  - url: last
    name: Last computing
